### ISSUE TITLE
Problems on mouseover

### ISSUE THREAD

**Issue by juanbrujo** [jcblw/zoomy-plugin#1]
Using mouseover, and while images are been loaded and the mouse is over the images, then when finished the zoom isn't activated

**Comment by jcblw** [comment]
i have not been able to replicate this issue. I do not know if my images loading to fast or what. Can you set up a test page that exhibits this behavior.

_Heres the page i tried it out on_

http://redeyeoperations.com/dev/

**Comment by juanbrujo** [comment]
This same one (production):

http://www.gacel.cl/zapato/planas-plana-46/

**Comment by jcblw** [comment]
please download and update your js and css to the current  _version 1.3.3_.

Your running into a latency issue that has been solved in 1.3. Sorry I need to update the site.
