### ISSUE TITLE
Zoomy not working on Chrome

### ISSUE THREAD

**Issue by simpleex** [jcblw/zoomy-plugin#10]
Zoomy works locally but not on my server using Chrome.
Everything is ok with Firefox an IE...

Test URL : http://apps.coyote.fr/urap1/

Thx !

**Comment by jcblw** [comment]
Im on Chrome  26.0.1410.63 on linux and its working fine, also tested it out on mobile Chrome and mobile Chrome beta. All are fully functional.

What build and OS are you using?

**Comment by simpleex** [comment]
OK !
I tried on three different machines (PC Chrome 26.0.1410.64 m), the problem was an extension !!  Sorry for that...

**Comment by jcblw** [comment]
ah yes ad blockers, some do not play nice with the plugin and i have no idea why

**Comment by simpleex** [comment]
DoNotTrackMe was the guilty one, made me loose a few hours...
