### ISSUE TITLE
Opera Browser issue

### ISSUE THREAD

**Issue by krogalski** [jcblw/zoomy-plugin#16]
Hello, 
Opera Browser doesn't support transform translate3d property! So in zoomy.min.js You have to change values in this lines:

Find:
var b="translate3d("+a[2]+"px, "+a[3]+"px, 0)";

Change with:
var b="translate("+a[2]+"px, "+a[3]+"px)";

There is also a bug in this line:
A?{"-webkit-transform":b,"-moz-transform":b,"-ms-tranform":b,"-o-tranform":b,transform:b}:{top:a[3]+"px",left:a[2]+"px"})

there is a word "tranform" just change this with "transform"

**Comment by jcblw** [comment]
It looks like current version does work with it http://caniuse.com/#feat=transforms3d does fixing the misspelling fix the issue?
