### ISSUE TITLE
Zoomy in responsive layout?

### ISSUE THREAD

**Issue by niallthompson** [jcblw/zoomy-plugin#3]
Great plugin guys,

Do you know if it can be incorporated into a responsive layout?

I'm trying to integrate it with Flexslider gallery.

**Comment by jcblw** [comment]
yeah the code in [test branch](https://github.com/jacoblwe20/zoomy-plugin/tree/test) is, its unstable code though. Its just buggy in mobile touch phones but works really well on desktops.

**Comment by niallthompson** [comment]
great that you got it working in a responsive setup but it doesn't like it in the flexslider gallery. somewhere the code is clashing...

**Comment by jcblw** [comment]
Can you verify that the errors are from Zoomy?
