### ISSUE TITLE
zoomy in Ajax usage

### ISSUE THREAD

**Issue by pixeline** [jcblw/zoomy-plugin#5]
hello!

I'm using zoomy as part of a picture gallery, where user clicks on thumbnails and it replace the current image with the thumb's "large" and "full" size image urls. problem is: zoomy instance is not aware of the change.

So i tried recalling zoomy after the image change, but then the zoomy ui add up and break the layout.

I tried using the killZoomy function but so far, that breaks everything.

I'm not through trying stuff but i thought i'd ask: do you have a suggestion on how to do this properly so that zoomy detects the change in the DOM and adapt accordingly?

**Comment by jcblw** [comment]
Interesting...

I have used Zoomy with ajax and have also had multiple people use it with various sliders and galleries. The best method I have used is to recall Zoomy. If the image is the only thing in the layout that is switched then there needs to be a bit of cleanup to clean out some of the previous Zoomy UI elements. Kill Zoomy should have worked but it might not be enough. If you could share a link of the plugin making multiple call and breaking the UI im sure i could help you out further.

**Comment by pixeline** [comment]
Hello Jacob,

I did indeed find how to work it out, here is a snippet showing how i used it:

``` javascript
$('#product-gallery a').bind('click', function(e) {
        e.preventDefault();
        var $this = $(this);
        $('#product-gallery li').removeClass('current');
        $this.parent().addClass('current');
        $('#waiting').show();


        var img = new Image();
        img.src = $this.data('url');
        img.onload = function() {
            $('#waiting').hide();
            $('#product-image img:first')
                .attr('src', $this.data('url'))
            $('#viewer').attr('href',$this.data('full'));
            $('#viewer').killZoomy();
            $('#viewer').zoomy('mouseover', {zoomSize: 260,round: false,glare: false,clickable: false,border: "1px solid #111",attr: 'href'});
            Shadowbox.clearCache();
            Shadowbox.setup();
        };
    });

    // IMG ZOOM
    $('#viewer').zoomy('mouseover', {
        zoomSize: 260,
        round: false,
        glare: false,
        clickable: false,
        border: "1px solid #111",
        attr: 'href'
    });
```
