### ISSUE TITLE
zoom-obj background offset is totally wrong

### ISSUE THREAD

**Issue by kasper21** [jcblw/zoomy-plugin#7]
Hi Jacob,

I´m implementing your plugin and get this strange offset here: http://tabularasa-ny.com/tr/?p=421

any help would be appreciated.

thanks,
Kasper

![Screen Shot 2013-01-16 at 4 00 30 PM](https://f.cloud.github.com/assets/588803/72919/36199fea-6028-11e2-8be2-6c36bbc029ec.jpg)

**Comment by jcblw** [comment]
@kasper21 I visited your site and it looks like its lined up

![Screenshot from 2013-01-16 18-10-37](https://f.cloud.github.com/assets/578259/73523/92150fdc-604b-11e2-8f88-e93cb2b47cd3.jpg)

Is there any special conditions that are causing the behavior you have shown me above(eg. browser, os, mobile?), or have you figured out the issue let me know 

thanks
